sudo: required
dist: trusty
language: generic
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - ROS_REPO=ros
  matrix:
    - ROS_DISTRO=kinetic UPSTREAM_WORKSPACE=file
    #- ROS_DISTRO=kinetic UPSTREAM_WORKSPACE=file CATKIN_PARALLEL_JOBS='-p1' ROS_PARALLEL_JOBS='-j1' DOCKER_RUN_OPTS='-e ROS_MAVEN_DEPLOYMENT_REPOSITORY=/root/.m2/repository' VERBOSE_OUTPUT=false
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
#  - ./travis.sh  # Enable this when you have a package-local script 

